### ISSUE TITLE
volunteering as maintainer

### ISSUE THREAD

**Issue by ap--** [conda-forge/universal_pathlib-feedstock#14]
Hi @andrewfulton9

I'm happy to be added as a maintainer.

Cheers,
Andreas 😃

**Comment by andrewfulton9** [comment]
Hi @ap--, I'm sorry I should have taken care of this a long time ago, but are you still interested in being a maintainer?

**Comment by ap--** [comment]
Hi @andrewfulton9,

no worries ☺️ 
Yes, I'm still interested.

Cheers,
Andreas

**Comment by andrewfulton9** [comment]
Great! I just opened #26, the conda-forge bot should take care of it shortly. Thanks a lot for volunteering!

**Comment by andrewfulton9** [comment]
@ap--, you should be all good to go as a maintainer so I am going to go ahead and close this issue. Thanks again!

**Comment by ap--** [comment]
Thanks Andrew!
